### ISSUE TITLE
windmill graph is missing an input field

### ISSUE THREAD

**Issue by Ndolam** [Razmataz88/Graphic#3]
OK, this is probably my fault, but anyway...
The original submission to github has a problem in that when you select Dutch Windmill
there is only one input (blades) and none for the number of nodes per blade.

**Comment by Ndolam** [comment]
Since I broke it, I fixed it.  (My commit 73fe104308d0f39fe1c696fb712fb0b00ea7ebe0 )

**Comment by Razmataz88** [comment]
Thank you for the fix. : )
