### ISSUE TITLE
antiprism scaling problem

### ISSUE THREAD

**Issue by Ndolam** [Razmataz88/Graphic#4]
Only the outer triangle of the 6-node antiprism scales, the inner triangle stays fixed in size.

**Comment by Razmataz88** [comment]
This bug cannot be reproduced. Several different values were used for the height and width of an anti-prism and the inner and outer triangles scale accordingly.

please see image for reference (bottom graph is 3in by 3in, top graph is 6in by 6in)
<img width="984" alt="screen shot 2016-02-15 at 6 33 40 pm" src="https://cloud.githubusercontent.com/assets/7534675/13062211/32613cac-d413-11e5-802a-ec99f7d2f218.png">

If the bug persists please provide some steps to reproduce the bug

**Comment by Ndolam** [comment]
Fixed in one of my commits about 9 days ago.

**Comment by Razmataz88** [comment]
Thank you for the fix
